### ISSUE TITLE
Could not find any downloads that satisfy the requirement requirements.txt

### ISSUE THREAD

**Issue by pwneddesal** [TheBlusky/pickle-prick#1]
can you help me with this. thanks 💃 
![image](https://user-images.githubusercontent.com/6646675/34553872-cdedbd42-f164-11e7-960d-e43cacfd1a9c.png)

**Comment by TheBlusky** [comment]
You should use "-r" in order to install whole requirements file :

```
pip install -r requirements.txt
```

You can see this here https://github.com/TheBlusky/pickle-prick/blob/master/Dockerfile#L5 :-)

Did I mention a wrong command line somewhere ?

**Comment by pwneddesal** [comment]
@TheBlusky no, nothing I have just tried to run the vulnerable app without docker, thanks
